import Head from "next/head";
import { Inter } from "next/font/google";
import HeaderComponents from "@/Components/Header/HeaderComponents";
import BannerComponents from "@/Components/Banner/BannerComponents";
import SmallCardsComponents from "@/Components/Cards/SmallCardsComponents";
import MediumCardComponents from "@/Components/Cards/MediumCardComponents";
import LargeCardComponents from "@/Components/Cards/LargeCardComponents";
import FooterComponents from "@/Components/Footer/FooterComponents";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ exploreData, liveAnyWhereData }) {
  return (
    <div className="">
      <Head>
        <title>Airbnb App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <HeaderComponents />
      {/* Banner */}
      <BannerComponents />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        {/* Explore Nearby Section */}
        <section className="pt-5">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          {/* Pull sone data from a server - API endpoints */}

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {exploreData?.map((data) => (
              <SmallCardsComponents key={data?.img} data={data} />
            ))}
          </div>
        </section>

        {/* Live Anywhere Section */}

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-4 overflow-x-scroll scrollbar-hide p-3 ml-3">
            {liveAnyWhereData?.map(({ img, title }) => (
              <MediumCardComponents key={img} img={img} title={title} />
            ))}
          </div>
        </section>

        {/* Large Card */}

        <LargeCardComponents
          img="https://a0.muscache.com/im/pictures/2da67c1c-0c61-4629-8798-1d4de1ac9291.jpg?im_w=1440"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>

      <FooterComponents />
    </div>
  );
}

export async function getStaticProps() {
  // Fetch Data To Small Card Explore Nearby
  const res = await fetch("https://www.jsonkeeper.com/b/4G1G");
  const exploreData = await res.json();
  // Fetch Data To Big Card Live Anywhere
  const cardResponse = await fetch("https://www.jsonkeeper.com/b/VHHT");
  const liveAnyWhereData = await cardResponse.json();
  return {
    props: {
      exploreData,
      liveAnyWhereData,
    },
  };
}
